CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    identificador VARCHAR(14) NOT NULL UNIQUE,
    tipo_usuario VARCHAR(2) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_exclusao TIMESTAMP NULL,
    CONSTRAINT ck_usuario_tipo
    CHECK (tipo_usuario IN ('PF', 'PJ')),
    CONSTRAINT ck_usuario_identificador
    CHECK (
    (tipo_usuario = 'PF' AND LENGTH(identificador) = 11)
    OR
    (tipo_usuario = 'PJ' AND LENGTH(identificador) = 14)
    )
    );

CREATE TABLE IF NOT EXISTS carteiras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE,
    saldo_reais DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    saldo_dolares DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_carteira_usuario
    FOREIGN KEY (usuario_id)
    REFERENCES usuarios (id),

    CONSTRAINT ck_carteira_saldo_reais
    CHECK (saldo_reais >= 0),

    CONSTRAINT ck_carteira_saldo_dolares
    CHECK (saldo_dolares >= 0)
    );
